-- install_registry.lua
-- Pastebin installer for NNA_REG (the N.N.A. registry).
-- Run on a fresh CC computer:
--   pastebin get <id> install
--   install
-- After install, the registry boots automatically every time the
-- computer powers on. To update later:
--   install update

local BASE = "https://raw.githubusercontent.com/alfaoz/postroom/main"

local FILES = {
  { src = "src/lib/crypto.lua",  dst = "/postroom/lib/crypto.lua"  },
  { src = "src/lib/wire.lua",    dst = "/postroom/lib/wire.lua"    },
  { src = "src/lib/common.lua",  dst = "/postroom/lib/common.lua"  },
  { src = "src/nna_reg.lua",     dst = "/postroom/nna_reg.lua"     },
}

local STARTUP = '-- generated by install_registry\nshell.run("/postroom/nna_reg.lua")\n'

local function fail(msg) print("[install] " .. msg); error(msg, 0) end

local function ensureDir(p)
  if p == "" then return end
  if not fs.exists(p) then fs.makeDir(p) end
end

local function fetch(srcRel, dst)
  local url = BASE .. "/" .. srcRel
  io.write("  " .. dst .. " ... ")
  local h, err = http.get(url)
  if not h then print("FAIL"); fail("http.get failed: " .. tostring(err)) end
  local body = h.readAll(); h.close()
  ensureDir(fs.getDir(dst))
  local f = fs.open(dst, "w")
  if not f then print("FAIL"); fail("cannot write " .. dst) end
  f.write(body); f.close()
  print("OK")
end

local args = { ... }
local mode = args[1] or "install"

print("Postroom — N.N.A. registry installer")
print(string.rep("-", 40))
if not http then fail("HTTP API disabled. Enable it and try again.") end

if mode == "update" then
  print("Update mode: re-fetching files (existing state preserved).")
else
  if fs.exists("/postroom/state.txt") then
    print("This computer already has a Postroom installation.")
    print("Pass `update` to re-fetch sources, or wipe /postroom first.")
    return
  end
  print("Installing fresh registry...")
end

for _, f in ipairs(FILES) do fetch(f.src, f.dst) end

local sf = fs.open("/startup.lua", "w")
sf.write(STARTUP); sf.close()
print("  /startup.lua ... OK")

print("")
print("Done. Reboot to start the registry.")
print("On first boot the registry will print:")
print("  - the staff terminal secret (copy this into NNA_STAFF)")
print("  - the bootstrap admin credentials (admin / changeme)")
print("Change the admin password on first sign-in via NNA_STAFF.")
