-- install_staff.lua
-- Pastebin installer for NNA_STAFF (the N.N.A. office staff terminal).
-- Run on a fresh CC computer with a wireless modem, disk drive, and
-- printer attached:
--   pastebin get <id> install
--   install
-- After install, the terminal boots automatically. On first boot it
-- will ask you to paste the staff terminal secret — that 64-character
-- hex string was printed by NNA_REG on its first boot.

local BASE = "https://raw.githubusercontent.com/alfaoz/postroom/main"

local FILES = {
  { src = "src/lib/crypto.lua",  dst = "/postroom/lib/crypto.lua"  },
  { src = "src/lib/wire.lua",    dst = "/postroom/lib/wire.lua"    },
  { src = "src/lib/common.lua",  dst = "/postroom/lib/common.lua"  },
  { src = "src/nna_staff.lua",   dst = "/postroom/nna_staff.lua"   },
}

local STARTUP = '-- generated by install_staff\nshell.run("/postroom/nna_staff.lua")\n'

local function fail(msg) print("[install] " .. msg); error(msg, 0) end

local function ensureDir(p)
  if p == "" or fs.exists(p) then return end
  fs.makeDir(p)
end

local function fetch(srcRel, dst)
  local url = BASE .. "/" .. srcRel
  io.write("  " .. dst .. " ... ")
  local h, err = http.get(url)
  if not h then print("FAIL"); fail("http.get failed: " .. tostring(err)) end
  local body = h.readAll(); h.close()
  ensureDir(fs.getDir(dst))
  local f = fs.open(dst, "w")
  if not f then print("FAIL"); fail("cannot write " .. dst) end
  f.write(body); f.close()
  print("OK")
end

print("Postroom — N.N.A. staff terminal installer")
print(string.rep("-", 44))
if not http then fail("HTTP API disabled. Enable it and try again.") end

local mode = ({ ... })[1] or "install"
if mode == "update" then
  print("Update mode: re-fetching files (state preserved).")
end

for _, f in ipairs(FILES) do fetch(f.src, f.dst) end

local sf = fs.open("/startup.lua", "w")
sf.write(STARTUP); sf.close()
print("  /startup.lua ... OK")

print("")
print("Done. Reboot to start the staff terminal.")
print("On first boot you'll be asked to paste the 32-byte staff secret")
print("printed by NNA_REG when it first booted.")
