-- install_domain.lua
-- Pastebin installer for any private domain server.
-- Run on a fresh CC computer with the install floppy in the drive:
--   pastebin get <id> install
--   install
-- For an existing install, pass `update` to refresh sources without
-- re-running the token consumption ceremony.

local BASE = "https://raw.githubusercontent.com/alfaoz/postroom/main"

local FILES = {
  { src = "src/lib/crypto.lua",       dst = "/postroom/lib/crypto.lua"      },
  { src = "src/lib/wire.lua",         dst = "/postroom/lib/wire.lua"        },
  { src = "src/lib/common.lua",       dst = "/postroom/lib/common.lua"      },
  { src = "src/lib/mail_server.lua",  dst = "/postroom/lib/mail_server.lua" },
  { src = "src/domain_srv.lua",       dst = "/postroom/domain_srv.lua"      },
  { src = "src/install_disk.lua",     dst = "/postroom/install_disk.lua"    },
}
local STARTUP = '-- generated by install_domain\nshell.run("/postroom/domain_srv.lua")\n'

local function fail(msg) print("[install] " .. msg); error(msg, 0) end

local function ensureDir(p)
  if p == "" or fs.exists(p) then return end
  fs.makeDir(p)
end

local function fetch(srcRel, dst)
  local url = BASE .. "/" .. srcRel
  io.write("  " .. dst .. " ... ")
  local h, err = http.get(url)
  if not h then print("FAIL"); fail("http.get failed: " .. tostring(err)) end
  local body = h.readAll(); h.close()
  ensureDir(fs.getDir(dst))
  local f = fs.open(dst, "w")
  if not f then print("FAIL"); fail("cannot write " .. dst) end
  f.write(body); f.close()
  print("OK")
end

local args = { ... }
local mode = args[1] or "install"

print("Postroom — Domain server installer")
print(string.rep("-", 36))
if not http then fail("HTTP API disabled. Enable it and try again.") end

if mode == "update" then
  print("Update mode: re-fetching files (state preserved).")
  for _, f in ipairs(FILES) do fetch(f.src, f.dst) end
  print("Done. Reboot to pick up the update.")
  return
end

if fs.exists("/postroom/state.txt") then
  print("This computer already has a Postroom installation.")
  print("Pass `update` to re-fetch sources, or wipe /postroom first.")
  return
end

print("Step 1 of 3: fetching source files from GitHub...")
for _, f in ipairs(FILES) do fetch(f.src, f.dst) end

print("")
print("Step 2 of 3: reading install floppy...")
local FLOPPY_PATHS = { "disk/postroom_install", "disk1/postroom_install",
                       "disk2/postroom_install", "disk3/postroom_install" }
local installPath
for _, p in ipairs(FLOPPY_PATHS) do
  if fs.exists(p) then installPath = p; break end
end
if not installPath then
  print("[install] No install floppy found. Insert the floppy and re-run.")
  return
end

local f = fs.open(installPath, "r")
local meta = textutils.unserialize(f.readAll() or ""); f.close()
if type(meta) ~= "table" or meta.type ~= "POSTROOM_INSTALL" then
  fail("floppy is not a Postroom install disk")
end
print("  domain=@" .. meta.domain .. ", op=" .. tostring(meta.op_username))

print("")
print("Step 3 of 3: consuming install token with " .. meta.registry_station .. "...")

package.path = package.path .. ";/postroom/lib/?.lua;/postroom/?.lua"
local crypto = require("crypto")
local wire   = require("wire")
local C      = require("common")

local _, _ = wire.openModem()
rednet.host(wire.PROTOCOL, "INSTALL:" .. tostring(os.getComputerID()))
local regId = rednet.lookup(wire.PROTOCOL, meta.registry_station)
if not regId then fail("registry " .. meta.registry_station .. " not found on rednet") end

local resp, err = wire.sendRequest(regId,
  "INSTALL:" .. tostring(os.getComputerID()),
  "POSTROOM/REG", "consume_install_token",
  { token = meta.token, computer_id = os.getComputerID(),
    requested_op_username = meta.op_username },
  meta.token, 8)
if not resp then fail("registry rejected the token: " .. tostring(err)) end

local sf = fs.open("/postroom/secret", "w")
sf.write(resp.shared_secret); sf.close()

C.saveTable("/postroom/config.txt", {
  domain           = meta.domain,
  station          = string.upper(meta.domain) .. "_SRV",
  registry_station = meta.registry_station,
  branding         = { display_name = meta.domain },
})

local opName = resp.op_username or meta.op_username
local hash = crypto.hashPassword(meta.domain, opName, resp.op_initial_password)
local today = os.day()
local state = {
  domain_meta = {
    domain_name = meta.domain, server_id = os.getComputerID(),
    is_public_server = false,
    registry_station = meta.registry_station,
    branding = { display_name = meta.domain },
    install = { installed_day = today, install_token = "(consumed)" },
  },
  users = {
    [opName] = { username = opName, password_hash = hash, created_day = today,
                 must_change_password = true, is_op = true,
                 is_deputy = false, is_system = false },
    pm = { username = "pm", is_system = true, created_day = today },
    abuse = { username = "abuse", is_system = true, created_day = today },
    noreply = { username = "noreply", is_system = true, created_day = today },
  },
  mailboxes = {
    [opName] = { inbox = {}, sent = {}, trash = {} },
    pm = { inbox = {}, sent = {}, trash = {} },
    abuse = { inbox = {}, sent = {}, trash = {} },
    noreply = { inbox = {}, sent = {}, trash = {} },
  },
  messages = {}, sessions = {}, audit_log = {},
  counters = { next_msg_id = 1, total_messages = 0, total_users = 4 },
  last_trash_purge_day = -1,
}
C.saveTable("/postroom/state.txt", state)

local startup = fs.open("/startup.lua", "w")
startup.write(STARTUP); startup.close()

print("")
print(string.rep("=", 48))
print("INSTALLATION COMPLETE")
print(string.rep("=", 48))
print("  Domain:       @" .. meta.domain)
print("  Op account:   " .. opName .. "@" .. meta.domain)
print("  Temp pw:      " .. resp.op_initial_password)
print("  *** WRITE THIS DOWN ***")
print("")
print("Your op account must change its password on first login.")
print("")
io.write("Reboot now? [Y/n]: ")
local k = (io.read() or ""):lower():sub(1, 1)
if k == "" or k == "y" then os.reboot() end
